=begin
#BrowserStack Api

#No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

OpenAPI spec version: 1.0.0

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: unset

=end

require 'spec_helper'
require 'json'

# Unit tests for SwaggerClient::AppAutomateApi
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'AppAutomateApi' do
  before do
    # run before each test
    @instance = SwaggerClient::AppAutomateApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of AppAutomateApi' do
    it 'should create an instance of AppAutomateApi' do
      expect(@instance).to be_instance_of(SwaggerClient::AppAutomateApi)
    end
  end

  # unit tests for list_builds
  # List all builds
  # 
  # @param [Hash] opts the optional parameters
  # @option opts [Integer] :limit How many items to return at one time (max 100)
  # @return [Array<AutomationBuildWrapper>]
  describe 'list_builds test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for upload_app
  # Upload app
  # 
  # @param [Hash] opts the optional parameters
  # @option opts [File] :file The app to upload.
  # @return [InlineResponse200]
  describe 'upload_app test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
